#!/bin/bash

# Wait for oneprovider readiness
RETRY_NUM=0
# Optional first argument
TIMEOUT=${1:-300}
while ! curl -fk -H "x-auth-token:$ONECLIENT_ACCESS_TOKEN" -X POST \
	"https://${ONECLIENT_PROVIDER_HOST}/api/v3/oneprovider/lookup-file-id/demo-space" \
      &> /tmp/curl-out; do
    RETRY_NUM=$((RETRY_NUM + 1))
    
    if ! ((RETRY_NUM % 15)); then
        echo -e "\e[1;33m"
        echo "-------------------------------------------------------------------------"
        echo "Awaiting for the demo environment to be set up..."
        echo "-------------------------------------------------------------------------"
        echo -e "\e[0m"
    fi
    
    if [[ ${RETRY_NUM} -eq ${TIMEOUT} ]]; then
        echo -e "\e[1;31m"
        echo "-------------------------------------------------------------------------"
        echo "ERROR: The demo environment failed to be set up within ${TIMEOUT} seconds, exiting."
        echo "-------------------------------------------------------------------------"
        echo -e "\e[0m"
        exit 1
    fi
    
    sleep 1;
done
