#!/bin/bash

# Optional first argument
TIMEOUT=${1:-600}

RETRY_NUM=0
while ! [ -d /mnt/oneclient/demo-space ]; do
    RETRY_NUM=$((RETRY_NUM + 1))

    if ! ((RETRY_NUM % 15)); then
        echo -e "\e[1;33m"
        echo "-------------------------------------------------------------------------"
        echo "Awaiting Oneclient readiness..."
        echo "-------------------------------------------------------------------------"
        echo -e "\e[0m"
    fi

    if [[ ${RETRY_NUM} -eq ${TIMEOUT} ]]; then
        echo -e "\e[1;31m"
        echo "-------------------------------------------------------------------------"
        echo "ERROR: Oneclient failed to mount the demo-space within ${TIMEOUT} seconds, exiting."
        echo "-------------------------------------------------------------------------"
        echo -e "\e[0m"
        exit 1
    fi

    sleep 1;
done

exit 0
