#!/bin/bash

source /root/demo-mode/better-curl.sh

ONEZONE_IP=$(getent hosts onezone.local | awk '{ print $1 }')

# Optional first argument
TIMEOUT=${1:-300}

RETRY_NUM=0
while ! [ -d /mnt/oneclient/demo-space ]; do
    RETRY_NUM=$((RETRY_NUM + 1))

    if ! ((RETRY_NUM % 15)); then
        echo -e "\e[1;33m"
        echo "-------------------------------------------------------------------------"
        echo "Awaiting Oneclient readiness..."
        echo "-------------------------------------------------------------------------"
        echo -e "\e[0m"
    fi

    if [[ ${RETRY_NUM} -eq ${TIMEOUT} ]]; then
        echo -e "\e[1;31m"
        echo "-------------------------------------------------------------------------"
        echo "ERROR: Oneclient failed to mount demo-space from Oneprovider ${ONECLIENT_PROVIDER_HOST}"
        echo "       within ${TIMEOUT} seconds, exiting."
        echo "-------------------------------------------------------------------------"
        echo -e "\e[0m"
        exit_and_kill_docker
    fi

    sleep 1;
done

exit 0
